#!/usr/bin/env python3
"""Generates an Icinga 2 config with N hosts x 15 services for scale tests.

Roughly 5% of services and 1% of hosts are in a problem state; outputs carry
perfdata and hosts have custom vars, so payload sizes resemble production.
Usage: generate.py [hosts] > scale.conf

The demo cluster's generator (demo/icinga/generate.py) reuses the outputs
below (`SERVICES`, `PROBLEMS`).
"""
import random
import sys

ROLES = ["web", "api", "db", "k8s", "mq", "cache", "lb", "edge", "backup", "storage"]
SERVICES = [
    ("ping4", "PING OK - Packet loss = 0%, RTA = 0.42 ms|rta=0.42ms;100;200;0 pl=0%;20;60;0"),
    ("ssh", "SSH OK - OpenSSH_9.6p1 (protocol 2.0)|time=0.012s;;;0;10"),
    ("load", "OK - load average 0.52, 0.48, 0.41|load1=0.52;8;12;0 load5=0.48;6;10;0 load15=0.41;4;8;0"),
    ("disk /", "DISK OK - free space: / 41 GiB (59% inode=91%)|/=29GiB;56;63;0;70"),
    ("disk /var", "DISK OK - free space: /var 120 GiB (63% inode=97%)|/var=70GiB;152;171;0;190"),
    ("memory", "OK - 71% used (11.3 GiB of 15.9 GiB)|used=12133171200B;13664501760;15374159872;0;17083817984"),
    ("ntp", "NTP OK: Offset 0.004 secs|offset=0.004s;60;120;"),
    ("procs", "PROCS OK: 312 processes|procs=312;400;500;0"),
    ("swap", "SWAP OK - 100% free (2047 MB out of 2047 MB)|swap=2147483648B;0;0;0;2147483648"),
    ("users", "USERS OK - 2 users currently logged in|users=2;20;50;0"),
    ("http", "HTTP OK: HTTP/1.1 200 OK - 4812 bytes in 0.041 second response time|time=0.041s;1;2;0 size=4812B;;;0"),
    ("cert", "SSL OK - Certificate valid until 2027-03-01 (147 days)|days=147;30;7;0"),
    ("backup", "OK - last backup 2h ago, 312 GiB|age=7200s;86400;172800;0"),
    ("raid", "OK - all 4 disks online"),
    ("smart", "OK - no SMART errors on 4 disks"),
]
PROBLEMS = {
    1: "WARNING - threshold exceeded|value=85;80;90;0;100",
    2: "CRITICAL - threshold exceeded|value=97;80;90;0;100",
    3: "UNKNOWN - plugin timed out after 30s",
}


def main(hosts):
    random.seed(42)
    print("/* Generated by contract/scale/generate.py: scale test fixtures. */")
    print("""
template Service "scale-service" {
  check_command = "dummy"
  check_interval = 300s
  retry_interval = 60s
  max_check_attempts = 3
}

apply Service for (name => cfg in host.vars.scale_services) {
  import "scale-service"
  vars.dummy_state = cfg.state
  vars.dummy_text = cfg.text
  assign where host.vars.scale_services
}
""")
    for i in range(hosts):
        role = ROLES[i % len(ROLES)]
        host_state = 2 if random.random() < 0.01 else 0
        entries = []
        for name, text in SERVICES:
            r = random.random()
            state = 2 if r < 0.02 else 1 if r < 0.04 else 3 if r < 0.05 else 0
            out = PROBLEMS.get(state, text).replace('"', "'")
            entries.append(f'    "{name}" = {{ state = {state}, text = "{out}" }}')
        print(f'''object Host "{role}-{i:04d}.prod.example.com" {{
  check_command = "dummy"
  check_interval = 300s
  retry_interval = 60s
  max_check_attempts = 3
  vars.dummy_state = {host_state}
  vars.dummy_text = "PING {'CRITICAL - Packet loss = 100%' if host_state else 'OK - Packet loss = 0%, RTA = 0.31 ms'}"
  address = "10.{i // 65536}.{(i // 256) % 256}.{i % 256}"
  vars.role = "{role}"
  vars.env = "prod"
  vars.rack = "r{i % 40:02d}"
  vars.team = "team-{i % 7}"
  vars.runbook = "https://wiki.example.com/runbooks/{role}"
  vars.scale_services = {{
{chr(10).join(entries)}
  }}
}}''')


if __name__ == "__main__":
    main(int(sys.argv[1]) if len(sys.argv) > 1 else 2000)
