//! Homebrew tap files: a cask for the macOS app and a formula for the Linux
//! build, generated from the release artifacts' checksums.

use std::path::Path;

use crate::release::{artifacts, sha256_hex};
use crate::{APP_ID, APP_NAME, DEFAULT_REPO, Flags, Result, VERSION, write};

/// Writes `Casks/icygui.rb` and, when Linux tarballs exist,
/// `Formula/icygui.rb` into the tap checkout at `--out`.
pub(crate) fn write_tap(flags: &Flags) -> Result<()> {
    let dist = flags.dist.as_deref().ok_or("--dist DIR is required")?;
    let out = flags.out.as_deref().ok_or("--out TAP_DIR is required")?;
    let repo = flags.repo.as_deref().unwrap_or(DEFAULT_REPO);
    let files = artifacts(dist)?;
    let find = |suffix: &str| {
        files
            .iter()
            .find(|path| path.to_string_lossy().ends_with(suffix))
            .map(|path| sha256_hex(path))
            .transpose()
    };

    let dmg = find(&format!("{APP_NAME}-{VERSION}-macos-universal.dmg"))?
        .ok_or("no universal macOS .dmg in --dist (build it with `package --universal`)")?;
    let cask_path = out.join(format!("Casks/{APP_NAME}.rb"));
    write(&cask_path, cask(repo, VERSION, &dmg, flags.notarized))?;
    println!("wrote {}", cask_path.display());

    let linux_x86 = find(&format!("{APP_NAME}-{VERSION}-linux-x86_64.tar.gz"))?;
    let linux_arm = find(&format!("{APP_NAME}-{VERSION}-linux-aarch64.tar.gz"))?;
    if linux_x86.is_some() || linux_arm.is_some() {
        let formula_path = out.join(format!("Formula/{APP_NAME}.rb"));
        write(
            &formula_path,
            formula(repo, VERSION, linux_x86.as_deref(), linux_arm.as_deref()),
        )?;
        println!("wrote {}", formula_path.display());
    }
    write_readme(out, repo)
}

/// The cask: installs the universal app from the GitHub release. Builds
/// that are not notarized get a postflight that clears the quarantine flag
/// (Gatekeeper would refuse the first launch otherwise); the download is
/// still pinned by `sha256`.
pub(crate) fn cask(repo: &str, version: &str, sha256: &str, notarized: bool) -> String {
    let unnotarized = if notarized {
        String::new()
    } else {
        format!(
            r##"
  # Not notarized (no Apple Developer ID yet): clear the quarantine flag so
  # Gatekeeper allows the first launch. The download is pinned by sha256.
  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{{appdir}}/{APP_NAME}.app"],
                   must_succeed: false
  end

  caveats <<~EOS
    {APP_NAME} is not notarized by Apple. This cask removes the quarantine
    flag after installing so macOS lets it start.
  EOS
"##
        )
    };
    format!(
        r#"# Generated by `cargo xtask homebrew` in {repo}; do not edit by hand.
cask "{APP_NAME}" do
  version "{version}"
  sha256 "{sha256}"

  url "https://github.com/{repo}/releases/download/v#{{version}}/{APP_NAME}-#{{version}}-macos-universal.dmg"
  name "{APP_NAME}"
  desc "Native desktop client for the Icinga 2 monitoring API"
  homepage "https://github.com/{repo}"

  livecheck do
    url :url
    strategy :github_latest
  end

  depends_on macos: ">= :ventura"

  app "{APP_NAME}.app"

  uninstall quit: "{APP_ID}"
{unnotarized}
  zap trash: [
    "~/Library/Application Support/{APP_ID}",
    "~/Library/Caches/{APP_ID}",
    "~/Library/LaunchAgents/{APP_ID}.plist",
    "~/Library/Logs/{APP_NAME}",
    "~/Library/Preferences/{APP_ID}.plist",
    "~/Library/Saved Application State/{APP_ID}.savedState",
  ]
end
"#
    )
}

/// The Linux formula: installs the prebuilt binary, desktop entry and icons.
pub(crate) fn formula(
    repo: &str,
    version: &str,
    sha256_x86_64: Option<&str>,
    sha256_aarch64: Option<&str>,
) -> String {
    let arch_block = |arch: &str, name: &str, sha: Option<&str>| {
        sha.map(|sha| {
            format!(
                "    on_{arch} do\n      url \"https://github.com/{repo}/releases/download/v#{{version}}/{APP_NAME}-#{{version}}-linux-{name}.tar.gz\"\n      sha256 \"{sha}\"\n    end\n"
            )
        })
        .unwrap_or_default()
    };
    let class = format!("{}{}", APP_NAME[..1].to_uppercase(), &APP_NAME[1..]);
    format!(
        r##"# Generated by `cargo xtask homebrew` in {repo}; do not edit by hand.
# Linux build. On macOS install the app instead: brew install --cask {APP_NAME}
class {class} < Formula
  desc "Native desktop client for the Icinga 2 monitoring API"
  homepage "https://github.com/{repo}"
  version "{version}"
  license "MIT"

  on_linux do
{intel}{arm}  end

  depends_on :linux

  def install
    bin.install "bin/{APP_NAME}"
    share.install Dir["share/*"]
  end

  test do
    assert_match version.to_s, shell_output("#{{bin}}/{APP_NAME} --version")
  end
end
"##,
        intel = arch_block("intel", "x86_64", sha256_x86_64),
        arm = arch_block("arm", "aarch64", sha256_aarch64),
    )
}

fn write_readme(out: &Path, repo: &str) -> Result<()> {
    let readme = format!(
        "# Homebrew tap for {APP_NAME}\n\n\
         [{APP_NAME}](https://github.com/{repo}) is a native desktop client for Icinga 2.\n\n\
         ```sh\n\
         brew install --cask {owner}/tap/{APP_NAME}   # macOS\n\
         brew install {owner}/tap/{APP_NAME}          # Linux\n\
         ```\n\n\
         The cask and formula are generated by the release workflow of {repo}.\n",
        owner = repo.split('/').next().unwrap_or(repo),
    );
    write(&out.join("README.md"), readme)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn cask_interpolates_ruby_version() {
        let cask = cask("alexykn/icygui", "1.2.3", "abc", true);
        assert!(!cask.contains("postflight"));
        assert!(cask.contains(r#"version "1.2.3""#));
        assert!(cask.contains(r#"sha256 "abc""#));
        assert!(cask.contains("download/v#{version}/icygui-#{version}-macos-universal.dmg"));
        assert!(cask.contains(r#"uninstall quit: "io.github.alexykn.icygui""#));
    }

    #[test]
    fn unnotarized_casks_clear_the_quarantine_flag() {
        let cask = cask("alexykn/icygui", "1.2.3", "abc", false);
        assert!(cask.contains("com.apple.quarantine"));
        assert!(cask.contains("#{appdir}/icygui.app"));
    }

    #[test]
    fn formula_includes_only_present_architectures() {
        let formula = formula("alexykn/icygui", "1.2.3", Some("x86"), None);
        assert!(formula.contains("class Icygui < Formula"));
        assert!(formula.contains("on_intel do"));
        assert!(formula.contains(r#"sha256 "x86""#));
        assert!(!formula.contains("on_arm do"));
        assert!(formula.contains("#{bin}/icygui --version"));
    }
}
